### PR TITLE
Update Readme to fix broken link

### PR DESCRIPTION
**Pull request by JulienRouse**
Add 'https://' in front of many links to fix the broken links

### CODE REVIEW

**Comment by JulienRouse** [comment]
Second commit is to change https to http for the copyright link

**Comment by mihaiolteanu** [comment]
Please consider fixing the merge conflicts first.

**Comment by JulienRouse** [comment]
Done sorry for the inconvenience!

**Comment by mihaiolteanu** [comment]
This is not a meaningful enough contribution. Seems to me you're just chasing 'reputation' here (not that there is to gain any).

If you have  some real contribution, feature request or found a limitation of the library, make a pull request or raise an issue. I will consider it.

**Comment by JulienRouse** [comment]
Ok was just trying to fix the broken links in your readme page, you can do it as well just fix it. It's annoying to follow a link to go to a 404 page. 

Also put a contrib page to your project with clear rules if you don't want people to do 'meaningless contribution' to a public project.

**Pull request closed without merging**
